#!/bin/sh
echo 'héllo wörld' | tr 'é' 'e'
echo 'héllo wörld' | tr -d 'éö'
echo 'héllo wörld' | tr 'a-zéö' 'A-ZÉÖ'
echo 'héllo wörld ÀÉ' | tr '[:lower:]' '[:upper:]'
echo 'HÉLLO ÀÉ' | tr '[:upper:]' '[:lower:]'
echo 'héllo wörld' | tr -C 'a-z\n' '_'
echo 'héllo wörld' | tr -Cd 'a-z\n'
echo 'héllo  wörld' | tr -s ' '
echo 'ééé aaa' | tr -s 'é'
echo 'abc' | tr 'abc' 'αβγ'
echo 'αβγ' | tr 'αβγ' 'abc'
echo 'héllo 123' | tr -d '[:alpha:]'
echo 'héllo 123' | tr -cd '[:alpha:]\n'
echo 'a日b本c' | tr '日本' 'xy'
echo 'Ωmega' | tr 'Ω' 'o'
echo 'x→y' | tr '→' '-'
echo 'héllo' | tr -s 'l' 'ł'
echo 'grüße' | tr '[:lower:]' '[:upper:]'
echo 'αβγ δ' | tr -C 'α-ω\n' '*'
