#!/bin/sh
S="Hello World"
echo "${S:6}"
echo "${S:0:5}"
echo "${S: -5}"
echo "${S: -5:3}"
echo "${S:2:-3}"
echo "${S^^}"
echo "${S,,}"
L="shell"
echo "${L^}"
U="SHELL"
echo "${U,}"
echo "${S~~}"
N=S
echo "${!N}"
E=""
echo "${E:-empty}" "${E-unset}" "${UNSETV-unset}"
echo "${#S}"
